### ISSUE TITLE
(SystemJS) Can't resolve all parameters for ComponentLoaderFactory: (?, ?, ?, ?, ?).

### ISSUE THREAD

**Issue by amolbs2106** [valor-software/ng2-bootstrap#4494]
After adding 
import { BsDatepickerModule }   from 'ngx-bootstrap';
in app.modules m getting below error.

(index):26 Error: (SystemJS) Can't resolve all parameters for ComponentLoaderFactory: (?, ?, ?, ?, ?).
	Error: Can't resolve all parameters for ComponentLoaderFactory: (?, ?, ?, ?, ?).
	    at syntaxError (http://bacs.com/node_modules/@angular/compiler/bundles/compiler.umd.js:1725:34)
	    at CompileMetadataResolver._getDependenciesMetadata (http://bacs.com/node_modules/@angular/compiler/bundles/compiler.umd.js:15800:35)
	    at CompileMetadataResolver._getTypeMetadata (http://bacs.com/node_modules/@angular/compiler/bundles/compiler.umd.js:15668:26)
	    at CompileMetadataResolver._getInjectableMetadata (http://bacs.com/node_modules/@angular/compiler/bundles/compiler.umd.js:15654:21)
	    at CompileMetadataResolver.getProviderMetadata (http://bacs.com/node_modules/@angular/compiler/bundles/compiler.umd.js:15945:40)
	    at eval (http://bacs.com/node_modules/@angular/compiler/bundles/compiler.umd.js:15874:49)
	    at Array.forEach (<anonymous>)
	    at CompileMetadataResolver._getProvidersMetadata (http://bacs.com/node_modules/@angular/compiler/bundles/compiler.umd.js:15834:19)
	    at eval (http://bacs.com/node_modules/@angular/compiler/bundles/compiler.umd.js:15409:63)
	    at Array.forEach (<anonymous>)
	Evaluating http://bacs.com/src/main.js
	Error loading http://bacs.com/src/main.js
	    at syntaxError (http://bacs.com/node_modules/@angular/compiler/bundles/compiler.umd.js:1725:34)
	    at CompileMetadataResolver._getDependenciesMetadata (http://bacs.com/node_modules/@angular/compiler/bundles/compiler.umd.js:15800:35)
	    at CompileMetadataResolver._getTypeMetadata (http://bacs.com/node_modules/@angular/compiler/bundles/compiler.umd.js:15668:26)
	    at CompileMetadataResolver._getInjectableMetadata (http://bacs.com/node_modules/@angular/compiler/bundles/compiler.umd.js:15654:21)
	    at CompileMetadataResolver.getProviderMetadata (http://bacs.com/node_modules/@angular/compiler/bundles/compiler.umd.js:15945:40)
	    at eval (http://bacs.com/node_modules/@angular/compiler/bundles/compiler.umd.js:15874:49)
	    at Array.forEach (<anonymous>)
	    at CompileMetadataResolver._getProvidersMetadata (http://bacs.com/node_modules/@angular/compiler/bundles/compiler.umd.js:15834:19)
	    at eval (http://bacs.com/node_modules/@angular/compiler/bundles/compiler.umd.js:15409:63)
	    at Array.forEach (<anonymous>)
	Evaluating http://bacs.com/src/main.js
	Error loading http://bacs.com/src/main.js

**Comment by Joklogh** [comment]
Hi @amolbs2106 
Are using SystemJS or angular-cli?
Did you set up ngx-bootstrap according to the Getting Started section on the website?

**Comment by amolbs2106** [comment]
Hi @Joklogh 
 m using systemJS. Yes i have set up ngx-bootstrap according to getting started section.

Thanks

**Comment by jordanluyke** [comment]
Having same problem with v3

In my systemJS:
```
    "ngx-bootstrap": {
        main: "bundles/ngx-bootstrap.umd.min.js",
        defaultExtension: "js"
    },
```

**Comment by styxiak** [comment]
Integration with angular seed. Angular version 6:
```
With AlertModule:
partners:94 Error: Can't resolve all parameters for e: (?, ?).
  Evaluating http://localhost:5555/app/main.js
  Loading app/main
    at syntaxError (util.ts:100)
    at CompileMetadataResolver._getDependenciesMetadata (metadata_resolver.ts:959)
    at CompileMetadataResolver._getTypeMetadata (metadata_resolver.ts:839)
    at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (metadata_resolver.ts:380)
    at CompileMetadataResolver._getEntryComponentMetadata (metadata_resolver.ts:1070)
    at eval (metadata_resolver.ts:659)
    at Array.map (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (metadata_resolver.ts:659)
    at CompileMetadataResolver.getNgModuleSummary (metadata_resolver.ts:453)
    at eval (metadata_resolver.ts:551) "Not expecting this error? Report it at https://github.com/mgechev/angular-seed/issues"
```

**Comment by BoykoAlex** [comment]
Any news on this? Workarounds?
My workaround was transpile the es2015 file with SystemJS Babel transpiler plugin. It worked great, but in Chrome in Windows Browser-Sync get confused by the transpiled file at runtime and keeps reloading the page forever...

**Comment by archpollux** [comment]
My solution was to have `@Inject` on all constructor parameters that needed to be injected.

**Comment by Valery-vs** [comment]
+1

**Comment by tiagomsmagalhaes** [comment]
I'm getting this with Meteor 1.6.1.3 and Angular 6

**Comment by Domainv** [comment]
soon be fixed in new release
