### ISSUE TITLE
fullTemplateTypeCheck: Cannot read property 'type' of null

### ISSUE THREAD

**Issue by Domainv** [valor-software/ng2-bootstrap#4651]
[angular/angular#19906](https://github.com/angular/angular/issues/19906)

[angular/angular#24143](https://github.com/angular/angular/issues/24143)

Issue happens when fullTemplateTypeCheck is enabled.

```
Error: TypeError: Cannot read property 'type' of null
    at C:\projects\material2\node_modules\@angular\compiler\bundles\compiler.umd.js:25385:26
    at Array.forEach (native)
    at removeSummaryDuplicates (C:\projects\material2\node_modules\@angular\compiler\bundles\compiler.umd.js:25384:11)
    at TemplateParser.tryParseHtml (C:\projects\material2\node_modules\@angular\compiler\bundles\compiler.umd.js:24393:51)
    at TemplateParser.tryParse (C:\projects\material2\node_modules\@angular\compiler\bundles\compiler.umd.js:24370:21)
    at TemplateParser.parse (C:\projects\material2\node_modules\@angular\compiler\bundles\compiler.umd.js:24332:44)
    at AotCompiler._parseTemplate (C:\projects\material2\node_modules\@angular\compiler\bundles\compiler.umd.js:29710:60)
    at AotCompiler._compileComponent (C:\projects\material2\node_modules\@angular\compiler\bundles\compiler.umd.js:29682:23)
    at C:\projects\material2\node_modules\@angular\compiler\bundles\compiler.umd.js:29528:55
    at Array.forEach (native)
```

**Temporary fixed by setting fullTemplateTypeCheck: false**

**Version Information**

```
`Angular CLI: 6.1.5
Node: 8.11.3
OS: linux x64
Angular: 6.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
    @angular-devkit/build-angular: 0.6.1
    @angular/animations: 6.0.1
    @angular/cli: 6.1.5
    @angular/common: 6.0.1
    @angular/compiler: 6.0.1
    @angular/compiler-cli: 6.0.1
    rxjs                              6.1.0
   typescript                        2.7.2
   webpack                           4.8.3`

```

**Comment by dherges** [comment]
Hi @Domainv, did you figure out which parts of the source code trigger the error? I couldn't until now in a ~35 module, 150+ components library.
