### ISSUE TITLE
Error: Position is out of the list

### ISSUE THREAD

**Issue by santhoshraju621** [valor-software/ng2-bootstrap#5198]
Hi i am using ng-x bootstrap in my application when i am trying to launch.

it is givng me the following error. 
 

> Error: Position is out of the list
    at LinkedList.remove (/var/lib/jenkins/jobs/Angular/workspace/node_modules/ngx-bootstrap/utils/bundles/ngx-bootstrap-utils.umd.js:353:27)
    at CarouselComponent.removeSlide (/var/lib/jenkins/jobs/Angular/workspace/node_modules/ngx-bootstrap/carousel/bundles/ngx-bootstrap-carousel.umd.js:192:34)
    at SlideComponent.ngOnDestroy (/var/lib/jenkins/jobs/Angular/workspace/node_modules/ngx-bootstrap/carousel/bundles/ngx-bootstrap-carousel.umd.js:497:31)
    at callProviderLifecycles (/var/lib/jenkins/jobs/Angular/workspace/node_modules/@angular/core/bundles/core.umd.js:21009:22)
    at callElementProvidersLifecycles (/var/lib/jenkins/jobs/Angular/workspace/node_modules/@angular/core/bundles/core.umd.js:20977:17)
    at callLifecycleHooksChildrenFirst (/var/lib/jenkins/jobs/Angular/workspace/node_modules/@angular/core/bundles/core.umd.js:20967:33)
    at destroyView (/var/lib/jenkins/jobs/Angular/workspace/node_modules/@angular/core/bundles/core.umd.js:22029:9)
    at callViewAction (/var/lib/jenkins/jobs/Angular/workspace/node_modules/@angular/core/bundles/core.umd.js:22155:17)
    at execEmbeddedViewsAction (/var/lib/jenkins/jobs/Angular/workspace/node_modules/@angular/core/bundles/core.umd.js:22098:21)
    at destroyView (/var/lib/jenkins/jobs/Angular/workspace/node_modules/@angular/core/bundles/core.umd.js:22027:9)

Please help me to resolve

**Comment by Domainv** [comment]
@santhoshraju621 Please provide repo of reproduction, needs more info

**Comment by santhoshraju621** [comment]
@Domainv sorry man i don,t know how it is resolved but it is resolved automatically without any changes in code

**Comment by Domainv** [comment]
Great)

**Comment by kunalfleethawks** [comment]
Magic!! I am facing same problem. 

```
Error: Position is out of the list
    at LinkedList.remove (/var/task/dist/server.js:169346:19)
    at CarouselComponent.removeSlide (/var/task/dist/server.js:168435:26)
    at SlideComponent.ngOnDestroy (/var/task/dist/server.js:168960:23)
    at callProviderLifecycles (/var/task/dist/server.js:50395:18)
    at callElementProvidersLifecycles (/var/task/dist/server.js:50363:13)
    at callLifecycleHooksChildrenFirst (/var/task/dist/server.js:50353:29)
    at destroyView (/var/task/dist/server.js:58549:5)
    at callViewAction (/var/task/dist/server.js:58675:13)
    at execComponentViewsAction (/var/task/dist/server.js:58597:13)
    at destroyView (/var/task/dist/server.js:58548:5)
```
