### ISSUE TITLE
Documentation - Specify that typeahead [(ngModel)] parameter is required

### ISSUE THREAD

**Issue by youngpayters** [valor-software/ng2-bootstrap#5769]
Bug description:

My use case for typeahead module was rather than setting the ngModel for selected value, instead I was going to leverage the typeaheadOnSelect to set values to my reactive form and never setting the [(ngModel)] as it wasn't needed.

However I was getting very cryptic error messages and doesn't really lend to know what is actually the problem.

```
core.js:4080 ERROR NullInjectorError: R3InjectorError(AppModule)[NgControl -> NgControl -> NgControl]: 
  NullInjectorError: No provider for NgControl!
    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (http://localhost:4500/vendor.js:46350:25)
    at R3Injector.push../node_modules/@angular/core/fesm5/core.js.R3Injector.get (http://localhost:4500/vendor.js:56838:33)
    at R3Injector.push../node_modules/@angular/core/fesm5/core.js.R3Injector.get (http://localhost:4500/vendor.js:56838:33)
    at R3Injector.push../node_modules/@angular/core/fesm5/core.js.R3Injector.get (http://localhost:4500/vendor.js:56838:33)
    at NgModuleRef$1.push../node_modules/@angular/core/fesm5/core.js.NgModuleRef$1.get (http://localhost:4500/vendor.js:70308:33)
    at Object.get (http://localhost:4500/vendor.js:68551:35)
    at getOrCreateInjectable (http://localhost:4500/vendor.js:49224:39)
    at Module.ɵɵdirectiveInject (http://localhost:4500/vendor.js:59734:12)
    at NodeInjectorFactory.TypeaheadDirective_Factory [as factory] (http://localhost:4500/vendor.js:205983:655)
    at getNodeInjectable (http://localhost:4500/vendor.js:49332:44)
``` 

Plunker/StackBlitz that reproduces the issue:

Doesn't look like the starter project for this is somewhat old.

This is basically the layout I had:

```
  <input
    id="select"
    [typeahead]="options"
    (typeaheadOnSelect)="onSelect($event)"
    placeholder="Search for Options..."
    class="form-control"
  />
```

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 5.1.0

Angular: 9.1.2

Bootstrap: 4.4.1

**Comment by Maveric196** [comment]
Have you imported ReactiveFormsModule?
import { ReactiveFormsModule } from '@angular/forms';

**Comment by youngpayters** [comment]
Yes, I've been using this library for some time, just first time using the typeahead module.

I've been able to fix it by inserting `[(ngModel)]` to the template but that wasn't really clear from the documentation.

**Comment by AsankaMawilmada** [comment]
I have also bumped to same issue today, it seems you need both FormsModule & ReactiveFormsModule imported in the module
import { FormsModule, ReactiveFormsModule } from '@angular/forms';

imports: [
...
    FormsModule,
    ReactiveFormsModule,
...
    TypeaheadModule.forRoot()
  ],

Cheers

**Comment by oliverw** [comment]
Same problem.

**Comment by Chealer** [comment]
I suppose there are 2 aspects to this issue. For sure, as you report, this should be documented, but the code should also validate the presence of required parameters and fail cleanly when the tag is invalid.
