### ISSUE TITLE
Build error using Angular 9.1.3 - "let-" is only supported on ng-template elements.

### ISSUE THREAD

**Issue by rallets** [valor-software/ng2-bootstrap#5777]
Hi, I get a build error using latest version and Angular 9.1.3. With 9.0.3 it builds fine.
"let-" is only supported on ng-template elements.
I don't see any other issues regarding this, is it a know problem?
Thank you

More details:
```
Compiling ng-bootstrap : module as esm5
Error: Error on worker #7: Error: Template parse errors:
"let-" is only supported on ng-template elements. ("</b></small>\n      </th>\n    </tr>\n  </thead>\n  <tbody>\n    <template ngFor [ngForOf]=\"rows\" [ERROR ->]let-rowz=\"$implicit\" let-index=\"index\">\n      <tr *ngIf=\"!(datePicker.onlyCurrentMonth && rowz["): C:/[...]/ClientApp/node_modules/ng-bootstrap/datepicker/daypicker.component.js@110:1658
"let-" is only supported on ng-template elements. ("h>\n    </tr>\n  </thead>\n  <tbody>\n    <template ngFor [ngForOf]=\"rows\" let-rowz=\"$implicit\" [ERROR ->]let-index=\"index\">\n      <tr *ngIf=\"!(datePicker.onlyCurrentMonth && rowz[0].secondary && rowz[6]"): C:/[...]/ClientApp/node_modules/ng-bootstrap/datepicker/daypicker.component.js@110:1681
    at syntaxError (C:\[...]\ClientApp\node_modules\@angular\compiler\bundles\compiler.umd.js:2845:21)
    at htmlAstToRender3Ast (C:\[...]\ClientApp\node_modules\@angular\compiler\bundles\compiler.umd.js:16355:19)
    at Object.parseTemplate (C:\[...]\ClientApp\node_modules\@angular\compiler\bundles\compiler.umd.js:19271:18)
    at ComponentDecoratorHandler._parseTemplate (C:\[...]\ClientApp\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\component.js:694:33)
    at ComponentDecoratorHandler._extractInlineTemplate (C:\[...]\ClientApp\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\component.js:671:33)
    at ComponentDecoratorHandler.analyze (C:\[...]\ClientApp\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\component.js:204:37)
    at NgccTraitCompiler.TraitCompiler.analyzeTrait (C:\[...]\ClientApp\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:345:40)
    at analyze (C:\[...]\ClientApp\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:297:58)
    at _loop_1 (C:\[...]\ClientApp\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:319:21)
    at NgccTraitCompiler.TraitCompiler.analyzeClass (C:\[...]\ClientApp\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:325:35)
    at ClusterMaster.onWorkerMessage (C:\[...]\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:168:27)
    at C:\[...]\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:52:95
    at ClusterMaster.<anonymous> (C:\[...]\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:248:57)
    at step (C:\[...]\ClientApp\node_modules\tslib\tslib.js:139:27)
    at Object.next (C:\[...]\ClientApp\node_modules\tslib\tslib.js:120:57)
    at C:\[...]\ClientApp\node_modules\tslib\tslib.js:113:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\[...]\ClientApp\node_modules\tslib\tslib.js:109:16)
    at EventEmitter.<anonymous> (C:\[...]\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:242:32)
    at EventEmitter.emit (events.js:200:13)
An unhandled exception occurred: NGCC failed.
```

```
[error] Error: NGCC failed.
    at NgccProcessor.process (C:\[...]\ClientApp\node_modules\@ngtools\webpack\src\ngcc_processor.js:76:19)
    at C:\[...]\ClientApp\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:579:31
    at SyncHook.eval [as call] (eval at create (C:\[...]\ClientApp\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:9:1)
    at SyncHook.lazyCompileHook (C:\[...]\ClientApp\node_modules\tapable\lib\Hook.js:154:20)
    at Object.webpack [as webpackFactory] (C:\[...]\ClientApp\node_modules\webpack\lib\webpack.js:55:30)
    at createWebpack (C:\[...]\ClientApp\node_modules\@angular-devkit\build-webpack\src\webpack\index.js:19:36)
    at Object.runWebpack (C:\[...]\ClientApp\node_modules\@angular-devkit\build-webpack\src\webpack\index.js:33:12)
    at SwitchMapSubscriber.project (C:\[...]\ClientApp\node_modules\@angular-devkit\build-angular\src\browser\index.js:130:32)
    at SwitchMapSubscriber._next (C:\[...]\ClientApp\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\operators\switchMap.js:49:27)
    at SwitchMapSubscriber.Subscriber.next (C:\[...]\ClientApp\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\Subscriber.js:66:18)
    at C:\[...]\ClientApp\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\util\subscribeToPromise.js:7:24
```

Can be related to this line in [daypicker.component.ts](https://github.com/valor-software/ngx-bootstrap/blob/development/src/datepicker/daypicker.component.ts)
```
<ng-template ngFor [ngForOf]="rows" let-rowz="$implicit" let-index="index">
```
that confuses the angular compiler?
What about replacing it with the not-de-sugared version?
```
<ng-template *ngFor="let rowz of rows; index as index">
```

**Comment by rallets** [comment]
Sorry, we figured out that the error was raised by an old ng-bootstrap package, instead of ngx-bootstrap. Removed that package all worked fine.
