### ISSUE TITLE
NullInjectorError: No provider for TabsetConfig!

### ISSUE THREAD

**Issue by cyrilfr** [valor-software/ng2-bootstrap#5787]
I'm using ngx-bootstrap 5.5.0 with Angular 8 and I've a runtime exception when using the `TabsModule`.

I want to display logs in my app so I created a logs component:

logs.module.ts:
```
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { TabsModule } from 'ngx-bootstrap/tabs';
import { LogsComponent } from './logs.component';

@NgModule({
  imports: [
    CommonModule,
    TabsModule.forRoot()
  ],
  declarations: [
    LogsComponent
  ],
  exports: [
    LogsComponent
  ]
})
export class LogsgModule { }
```
logs.component.html
```
<tabset>
    <tab heading="current-app">Basic content</tab>
    <tab heading="app-manager">Basic content 1</tab>
    <tab heading="kernel">Basic content 2</tab>
</tabset>
```
logs.component.ts
```
import { Component } from '@angular/core';

@Component({
  selector: 'app-logs',
  templateUrl: './logs.component.html',
  styleUrls: ['./logs.component.scss']
})
export class LogsComponent {

}
```

But when the component is displayed, It throws an exception:

```
  constructor: 'Error',
  promise: { __zone_symbol__state: 0 },
  rejection: {
    constructor: 'Error',
    name: 'NullInjectorError',
    ngTempTokenPath: null,
    ngTokenPath: '[array]',
    stack: 'NullInjectorError: StaticInjectorError(AppModule)[TabsetComponent -> TabsetConfig]: \n' +
      '  StaticInjectorError(Platform: core)[TabsetComponent -> TabsetConfig]: \n' +
      '    NullInjectorError: No provider for TabsetConfig!\n' +
      '    at NullInjector.push.NullInjector.get (file:///usr/lib/node/app/dist/main.b481ae6fc920799d1931.js:1155:25)\n' +
      '    at resolveToken (file:///usr/lib/node/app/dist/main.b481ae6fc920799d1931.js:12347:24)\n' +
      '    at tryResolveToken (file:///usr/lib/node/vesta-app/dist/main.b481ae6fc920799d1931.js:12291:16)\n' +
      '    at StaticInjector.push.StaticInjector.get (file:///usr/lib/node/app/dist/main.b481ae6fc920799d1931.js:12193:20)\n' +
      '    at resolveToken (file:///usr/lib/node/app/dist/main.b481ae6fc920799d1931.js:12347:24)\n' +
      '    at tryResolveToken (file:///usr/lib/node/app/dist/main.b481ae6fc920799d1931.js:12291:16)\n' +
      '    at StaticInjector.push.StaticInjector.get (file:///usr/lib/node/app/dist/main.b481ae6fc920799d1931.js:12193:20)\n' +
      '    at resolveNgModuleDep (file:///usr/lib/node/app/dist/main.b481ae6fc920799d1931.js:20630:29)\n' +
      '    at NgModuleRef_.push.NgModuleRef_.get (file:///usr/lib/node/app/dist/main.b481ae6fc920799d1931.js:21305:16)\n' +
      '    at resolveNgModuleDep (file:///usr/lib/node/app/dist/main.b481ae6fc920799d1931.js:20630:29)'
  }
```

**Comment by cyrilfr** [comment]
I just had to import the `LogsModule`...
