### ISSUE TITLE
Angular 10 Error: Failed to find exported name of node (class ButtonRadioGroupDirective

### ISSUE THREAD

**Issue by azizkhani** [valor-software/ng2-bootstrap#5872]
"@ng-bootstrap/ng-bootstrap": "^7.0.0",

```
Compiling @ng-bootstrap/ng-bootstrap : es2015 as esm2015
Compiling ngx-bootstrap : es2015 as esm2015
Error: Error on worker #2: Error: Failed to find exported name of node (class ButtonRadioGroupDirective {
    constructor(el, cdr) {
        this.el = el;
        this.cdr = cdr;
        this.onChange = Function.prototype;
        this.onTouched = Function.prototype;
    }
    get value() {
        return this._value;
    }
    set value(value) {
        this._value = value;
    }
    writeValue(value) {
        this._value = value;
        this.cdr.markForCheck();
    }
    registerOnChange(fn) {
        this.onChange = fn;
    }
    registerOnTouched(fn) {
        this.onTouched = fn;
    }
}) in '/Users/azizkhani/Data/git/openprojects/enhancement-project/node_modules/ngx-bootstrap/bundles/ngx-bootstrap.es2015.js'.
    at Object.findExportedNameOfNode (/Users/azizkhani/Data/git/openprojects/enhancement-project/node_modules/@angular/compiler-cli/src/ngtsc/imports/src/find_export.js:36:19)
    at LogicalProjectStrategy.emit (/Users/azizkhani/Data/git/openprojects/enhancement-project/node_modules/@angular/compiler-cli/src/ngtsc/imports/src/emitter.js:229:38)
    at ReferenceEmitter.emit (/Users/azizkhani/Data/git/openprojects/enhancement-project/node_modules/@angular/compiler-cli/src/ngtsc/imports/src/emitter.js:72:44)
    at Object.toR3Reference (/Users/azizkhani/Data/git/openprojects/enhancement-project/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/util.js:193:31)
    at NgModuleDecoratorHandler._toR3Reference (/Users/azizkhani/Data/git/openprojects/enhancement-project/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:418:31)
    at /Users/azizkhani/Data/git/openprojects/enhancement-project/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:197:83
    at Array.map (<anonymous>)
    at NgModuleDecoratorHandler.analyze (/Users/azizkhani/Data/git/openprojects/enhancement-project/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:197:48)
    at NgccTraitCompiler.TraitCompiler.analyzeTrait (/Users/azizkhani/Data/git/openprojects/enhancement-project/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:346:40)
    at analyze (/Users/azizkhani/Data/git/openprojects/enhancement-project/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:298:58)
    at ClusterMaster.onWorkerMessage (/Users/azizkhani/Data/git/openprojects/enhancement-project/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:195:27)
    at /Users/azizkhani/Data/git/openprojects/enhancement-project/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:55:95
    at ClusterMaster.<anonymous> (/Users/azizkhani/Data/git/openprojects/enhancement-project/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:293:57)
    at step (/Users/azizkhani/Data/git/openprojects/enhancement-project/node_modules/@angular/compiler-cli/node_modules/tslib/tslib.js:140:27)
    at Object.next (/Users/azizkhani/Data/git/openprojects/enhancement-project/node_modules/@angular/compiler-cli/node_modules/tslib/tslib.js:121:57)
    at /Users/azizkhani/Data/git/openprojects/enhancement-project/node_modules/@angular/compiler-cli/node_modules/tslib/tslib.js:114:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/azizkhani/Data/git/openprojects/enhancement-project/node_modules/@angular/compiler-cli/node_modules/tslib/tslib.js:110:16)
    at EventEmitter.<anonymous> (/Users/azizkhani/Data/git/openprojects/enhancement-project/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:287:32)
    at EventEmitter.emit (events.js:315:20)
An unhandled exception occurred: NGCC failed.
See "/private/var/folders/_0/g0zwvkhj4nq2n01pxm8xgtn00000gn/T/ng-T5SnXJ/angular-errors.log" for further details.
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! EnhancementService@10.0.0 start: `ng serve --proxy-config proxy.conf.json`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the EnhancementService@10.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

```

**Comment by rodrigosanzlongone** [comment]
did you found the solution for this?
