### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'removeChild')

### ISSUE THREAD

**Issue by FrancescoBorzi** [valor-software/ng2-bootstrap#6358]
Bug description:

Unit tests fail with:

```
Chrome Headless 95.0.4638.69 (Linux x86_64) ERROR
  An error was thrown in afterAll
  TypeError: Cannot read properties of null (reading 'removeChild')
      at ComponentLoader.hide (http://localhost:9876/_karma_webpack_/webpack:/node_modules/ngx-bootstrap/__ivy_ngcc__/component-loader/fesm2015/ngx-bootstrap-component-loader.js:143:32)
      at BsModalService.removeBackdrop (http://localhost:9876/_karma_webpack_/webpack:/node_modules/ngx-bootstrap/__ivy_ngcc__/modal/fesm2015/ngx-bootstrap-modal.js:814:30)
      at apply (http://localhost:9876/_karma_webpack_/webpack:/node_modules/ngx-bootstrap/__ivy_ngcc__/modal/fesm2015/ngx-bootstrap-modal.js:745:31)
      at apply (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:2561:41)
      at ZoneDelegate.invokeTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:406:31)
      at ProxyZoneSpec.onInvokeTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone-testing.js:318:39)
      at ZoneDelegate.invokeTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:405:60)
      at Zone.runTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:178:47)
      at call (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:487:34)
      at ZoneTask.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:476:48)
  TypeError: Cannot read properties of null (reading 'removeChild')
      at ComponentLoader.hide (http://localhost:9876/_karma_webpack_/webpack:/node_modules/ngx-bootstrap/__ivy_ngcc__/component-loader/fesm2015/ngx-bootstrap-component-loader.js:143:32)
```

Issue reproduction:

https://github.com/azerothcore/Keira3/pull/1532

https://github.com/azerothcore/Keira3/runs/4133377142?check_suite_focus=true

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 7.1.0

Angular: 13

Bootstrap: 5

Build system: Angular CLI, System.js, webpack, starter seed: Angular CLI

**Expected behavior**

Should not error

**Comment by air2** [comment]
Same problem in  7.1.2

**Comment by FrancescoBorzi** [comment]
@SvetlanaMuravlova @valorkin @daniloff200 @MuravlovaSvetlana @ErikYu @samshay 

can anyone please have a look at this? it's currently failing our tests in a random fashion...

**Comment by SvetlanaMuravlova** [comment]
@FrancescoBorzi hi) thank you for issue. Try please angular 12 with such version of ngx-bootstrap.  Compatibility with angular 13 will be in the future version.

**Comment by FrancescoBorzi** [comment]
I'm now using version 8.0.0-RC4 with Angular 13 and unfortunately, the problem is still happening.

It doesn't fail consistently, just happens randomly from time to time, but often enough to be annoying. I set my unit tests with 5 re-try attempts but it still manages to fail, for example:

https://github.com/azerothcore/Keira3/runs/4631630164?check_suite_focus=true

```
  TypeError: Cannot read properties of null (reading 'removeChild')
      at ComponentLoader.hide (http://localhost:9876/_karma_webpack_/webpack:/node_modules/ngx-bootstrap/component-loader/fesm2020/ngx-bootstrap-component-loader.mjs:141:32)
      at BsModalService.removeBackdrop (http://localhost:9876/_karma_webpack_/webpack:/node_modules/ngx-bootstrap/modal/fesm2020/ngx-bootstrap-modal.mjs:768:30)
      at apply (http://localhost:9876/_karma_webpack_/webpack:/node_modules/ngx-bootstrap/modal/fesm2020/ngx-bootstrap-modal.mjs:700:31)
      at apply (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:2561:41)
      at ZoneDelegate.invokeTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:406:31)
      at ProxyZoneSpec.onInvokeTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone-testing.js:318:39)
      at ZoneDelegate.invokeTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:405:60)
      at Zone.runTask (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:178:47)
      at call (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:487:34)
      at ZoneTask.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/fesm2015/zone.js:476:48)
```

I think this issue should be reopened and prioritised @SvetlanaMuravlova @valorkin
