### ISSUE TITLE
Carousel: Cannot read properties of undefined (reading 'map') 

### ISSUE THREAD

**Issue by Splinteer** [valor-software/ng2-bootstrap#6431]
Hello,
I'm trying to use the carousel but I'm always getting this error:
```
ERROR TypeError: Cannot read properties of undefined (reading 'map')
    at CarouselComponent.getVisibleIndexes (ngx-bootstrap-carousel.mjs:658:18)
    at CarouselComponent.selectInitialSlides (ngx-bootstrap-carousel.mjs:432:41)
    at ngx-bootstrap-carousel.mjs:182:22
    at timer (zone.js:2561:1)
    at ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.mjs:25444:1)
    at ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at invokeTask (zone.js:487:1)
    at ZoneTask.invoke (zone.js:476:1)
```

Here is my template:
```
  <carousel [itemsPerSlide]="3">
    <slide *ngFor="let slide of slides">
      <img [src]="serverUrl + slide.url" alt="first slide" style="display: block; width: 100%" />
    </slide>
  </carousel>
```

Imported this to the appModule as .forRoot() and to my submodule without .forRoot()
`import { CarouselModule } from 'ngx-bootstrap/carousel';`

I already tried to copy paste component from stackblitz but I found no way to make it work.
Here is my stacks:

Angular: 13.1.0
ngx-bootstrap: 8.0.0

How to fix this ?

**Comment by SvetlanaMuravlova** [comment]
should be resolved in version 9.0.0, check please

**Comment by asadakkhan** [comment]
Not resolved

**Comment by ciaranj** [comment]
I'm seeing some very similar errors to this @10.2.0 (intermittently)

```
Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')
    at CarouselComponent.moveMultilist (ngx-bootstrap-carousel.mjs:648:70)
    at CarouselComponent.move (ngx-bootstrap-carousel.mjs:292:18)
    at CarouselComponent.nextSlideFromInterval (ngx-bootstrap-carousel.mjs:249:14)
    at ngx-bootstrap-carousel.mjs:700:34
    at _ZoneDelegate.invoke (zone.js:375:26)
    at Object.onInvoke (core.mjs:24210:33)
    at _ZoneDelegate.invoke (zone.js:374:52)
    at Zone.run (zone.js:134:43)
    at NgZone.run (core.mjs:24064:28)
    at ngx-bootstrap-carousel.mjs:695:33

```
and

```
ERROR TypeError: Cannot read properties of undefined (reading 'map')
    at CarouselComponent.getVisibleIndexes (ngx-bootstrap-carousel.mjs:656:18)
    at get isFirstSlideVisible [as isFirstSlideVisible] (ngx-bootstrap-carousel.mjs:157:30)
    at CarouselComponent.checkDisabledClass (ngx-bootstrap-carousel.mjs:724:88)
    at CarouselComponent_a_5_Template (ngx-bootstrap-carousel.mjs:28:100)
    at executeTemplate (core.mjs:10441:9)
    at refreshView (core.mjs:10326:13)
    at refreshEmbeddedViews (core.mjs:11339:17)
    at refreshView (core.mjs:10350:9)
    at refreshComponent (core.mjs:11385:13)
    at refreshChildComponents (core.mjs:10116:9)
```

Both seem to be de-referencing an empty this._chunkedSlides (notably this._slides is populated).  

Having traced the code through, it appears that in the case where things 'work' (no errors). 'chunkByNumber' is called *after* addSlide has been called for each carousel slide. 

In the case where things do not 'work' 'chunkByNumber is called *before* addSlide has been called. I imagine this is related to my use of ngFor over a list that the initial value of which is an empty list. Should the chunking primitives be re-calculated after each addSlide call perhaps? Or is this just a side-effect of my life-cycle. Does this component work with the 'slides' changing underneath it?

This is my markup:

```
    <carousel
              [interval]="1000"
              [itemsPerSlide]="3"
              [noWrap]="false"
              [noPause]="false"
              [showIndicators]= "false"
              [isAnimated]="true"
              [indicatorsByChunk]="true"
              >
      <slide *ngFor="let previousThing of previousThings; trackBy:identifyThing">
        {{ previousThing.label }}
      </slide> 
    </carousel>
```

This is a snippet of the relevant containing component:

```
  previousPrompts: PreviousPrompt[] = [];

  _updatePreviousThings() {
    this.apiService.getPreviousThings(this.index).subscribe(previousThings => {
      this.previousThings= previousThings;
    });
  }

  ngOnInit() {
    this._updatePreviousThings();
    const secondsCounter = interval(5000);
    secondsCounter.subscribe(() => {
      this._updatePreviousThings();
    });
  }

```
