### ISSUE TITLE
Exception while opening popover

### ISSUE THREAD

**Issue by rpastusz** [valor-software/ng2-bootstrap#6454]
**Bug description**

While opening popover, console shows exception :

Uncaught TypeError: Cannot read properties of undefined (reading 'match')
    at initData (ngx-bootstrap-positioning.js:852:1)
    at Positioning.positionElements (ngx-bootstrap-positioning.js:975:1)
    at positionElements (ngx-bootstrap-positioning.js:984:1)
    at ngx-bootstrap-positioning.js:1016:1
    at Map.forEach (<anonymous>)
    at Object.next (ngx-bootstrap-positioning.js:1015:1)
    at ConsumerObserver.next (Subscriber.js:91:1)
    at SafeSubscriber._next (Subscriber.js:60:1)
    at SafeSubscriber.next (Subscriber.js:31:1)
    at subscribe.innerComplete (mergeInternals.js:25:1)

**Versions of ngx-bootstrap, Angular, and Bootstrap:**

ngx-bootstrap: > 7.1 

Angular: 13.3.0

Bootstrap:  5.1.3

**Comment by rpastusz** [comment]
Fixed. I had placement="auto bottom" attribute added to html tag.
