### ISSUE TITLE
TypeError: sorted.map is not a function Typeahead

### ISSUE THREAD

**Issue by fzs1994** [valor-software/ng2-bootstrap#6456]
Getting this error in console:
`TypeError: sorted.map is not a function
    at TypeaheadDirective.prepareMatches (ngx-bootstrap-typeahead.js:2411:1)
    at TypeaheadDirective.finalizeAsyncCall (ngx-bootstrap-typeahead.js:2334:1)
    at SafeSubscriber._next (ngx-bootstrap-typeahead.js:2221:1)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:183:1)
    at SafeSubscriber.next (Subscriber.js:122:1)
    at Subscriber._next (Subscriber.js:72:1)
    at Subscriber.next (Subscriber.js:49:1)
    at SwitchMapSubscriber.notifyNext (switchMap.js:70:1)
    at InnerSubscriber._next (InnerSubscriber.js:11:1)
    at InnerSubscriber.next (Subscriber.js:49:1)`

![image](https://user-images.githubusercontent.com/10684213/163953701-2327e85c-90bb-4c1e-811d-ce8043359019.png)

ngx-bootstrap: ^6.0.0

Angular: ^9.1.6

Bootstrap: ^4.5.0

Build system: Angular CLI

**Comment by SvetlanaMuravlova** [comment]
@fzs1994 hi) thank you for your issue, but can you, please, add some details for reproducing such bug ?

**Comment by identiq** [comment]
I've found the issue
https://github.com/ng-select/ng-select is using the same `[typeahead]` directive as you and expects an Observable instead an Array, explaining `sorted.map is not a function` error
@SvetlanaMuravlova You should disable your directive if DOM container is `<ng-select>` and not `<input>`

@fzs1994 Meanwhile to avoid the error you can use `[typeaheadMinLength]="9999"` on `<ng-select>` components
