### ISSUE TITLE
cannot read properties of undefined (reading map)

### ISSUE THREAD

**Issue by Krishkumarchhabra25** [valor-software/ng2-bootstrap#6559]
Uncaught TypeError: Cannot read properties of undefined (reading 'map')
    at Slider (Slider.jsx:9:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at beginWork$1 (react-dom.development.js:27426:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)
    at recoverFromConcurrentError (react-dom.development.js:25850:1)
    at performSyncWorkOnRoot (react-dom.development.js:26096:1)
![2023-02-20 (1)](https://user-images.githubusercontent.com/123287035/219992302-7b2f77fb-9cde-4e25-b096-5bbc43f71a3b.png)
![2023-02-20 (2)](https://user-images.githubusercontent.com/123287035/219992313-9de0ff83-3a59-404e-ad1d-f7cdab6a204d.png)
![2023-02-20](https://user-images.githubusercontent.com/123287035/219992323-aff1b6fe-b22d-4673-b9e0-8c0f538b8b2e.png)

**Comment by SvetlanaMuravlova** [comment]
@krishchha, i can see you don't use our lib. Are you sure you created issue in correct repository, cause we don't support react-bootstrap?

**Comment by Krishkumarchhabra25** [comment]
> @krishchha, i can see you don't use our lib. Are you sure you created issue in correct repository, cause we don't support react-bootstrap?

sorry its my mistake
