### ISSUE TITLE
Modal in standalone component fails with injection error

### ISSUE THREAD

**Issue by maitredede** [valor-software/ng2-bootstrap#6692]
Hello,

Bug description:

When trying to use `BsModalService` in a standalone component, the injection fails :

```
NullInjectorError: R3InjectorError(Standalone[_AppComponent])[_BsModalService -> _BsModalService -> _BsModalService -> RendererFactory2]: 
  NullInjectorError: No provider for RendererFactory2!
    at NullInjector.get (core.mjs:1636:21)
    at R3Injector.get (core.mjs:3018:27)
    at injectInjectorOnly (core.mjs:1096:36)
    at ɵɵinject (core.mjs:1102:40)
    at Object.BsModalService_Factory [as factory] (ngx-bootstrap-modal.mjs:377:59)
    at core.mjs:3136:35
    at runInInjectorProfilerContext (core.mjs:867:5)
    at R3Injector.hydrate (core.mjs:3135:11)
    at R3Injector.get (core.mjs:3009:23)
    at R3Injector.get (core.mjs:3018:27)
```

Plunker/StackBlitz that reproduces the issue: https://stackblitz.com/edit/stackblitz-starters-9ts86x?file=src%2Fmain.ts

Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 18.1.1

Angular: 18.2.8

Bootstrap: 5.3.3

Build system: Angular CLI

**Expected behavior**

It is expected that dependency injection does not fail and that modal service works as expected.

**Comment by lexasq** [comment]
Hi, please refer to the documentation for this https://valor-software.com/ngx-bootstrap/#/components/modals?tab=api
You are now suppose to add BsModalService to providers for your standalone component.

**Comment by maitredede** [comment]
Thanks @lexasq

I added it to the global application providers, with the default config tuned for my needs :

```ts
export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes),
    provideAnimations(),

    //the fix from the docs https://valor-software.com/ngx-bootstrap/#/components/modals?tab=api
    BsModalService,
    {
      provide: APP_INITIALIZER,
      multi: true,
      deps: [BsModalService],
      useFactory: (bsModalService: BsModalService) => {
        return () => {
          bsModalService.config.animated = true;
          bsModalService.config.backdrop = "static";
          bsModalService.config.focus = true;
          bsModalService.config.ignoreBackdropClick = true;
          bsModalService.config.keyboard = false;
          bsModalService.config.class = "modal-xl";
        };
      }
    }
  ],
};
```

**Comment by adlh** [comment]
Thx to @maitredede for the global provider solution. 
I updated it to cope with the fact that the usage of `APP_INITIALIZER` is now deprecated on newer versions of angular (e.g. version 19):

```
// app.config.ts

const bsModalInitializer = (bsModalService: BsModalService) => {
    bsModalService.config.animated = true;
    bsModalService.config.backdrop = "static";
    bsModalService.config.focus = true;
    bsModalService.config.ignoreBackdropClick = true;
    bsModalService.config.keyboard = false;
    bsModalService.config.class = "modal-xl";
};

export const appConfig: ApplicationConfig = {
    providers: [
        // ...
        // The fix from the docs https://valor-software.com/ngx-bootstrap/#/components/modals?tab=api
        BsModalService,
        provideAppInitializer(() => bsModalInitializer(inject(BsModalService)))
    ]
};
```
